components:
  - canonical_name: docker-host-01
    type: host
    environment: production
    tenant: default
    service_tier: tier-1
    aliases:
      - alias: node-exporter:9100
        source_tool: prometheus
      - alias: docker-host-01
        source_tool: zabbix
      - alias: docker-host-01
        source_tool: trace

  - canonical_name: cart
    type: service
    environment: production
    tenant: default
    service_tier: tier-1
    aliases:
      - alias: cart
        source_tool: prometheus
      - alias: cart:8080
        source_tool: blackbox
      - alias: cart
        source_tool: trace
        
  - canonical_name: /mnt/valkey-data
    type: filesystem
    environment: production
    tenant: default
    service_tier: tier-1
    aliases:
      - alias: /mnt/valkey-data
        source_tool: prometheus
      - alias: /mnt/valkey-data
        source_tool: zabbix
      - alias: /mnt/valkey-data
        source_tool: trace

  - canonical_name: frontend
    type: service
    environment: production
    tenant: default
    service_tier: tier-1
    aliases:
      - alias: frontend
        source_tool: trace

  - canonical_name: valkey
    type: datastore
    environment: production
    tenant: default
    service_tier: tier-1
    aliases:
      - alias: valkey
        source_tool: trace

  - canonical_name: load-generator
    type: service
    environment: production
    tenant: default
    service_tier: tier-1
    aliases:
      - alias: load-generator
        source_tool: trace
