"""add component_unresolved to alerts

Revision ID: 4f8d089c4255
Revises: a3aab7f35f52
Create Date: 2026-08-22 12:20:38.428506

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8d089c4255"
down_revision: str | Sequence[str] | None = "a3aab7f35f52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("component_unresolved", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "component_unresolved")
    # ### end Alembic commands ###
