"""add signal_scores to incident_alerts

Revision ID: 5cca80ef12b0
Revises: 6e80d84ff9c2
Create Date: 2026-08-28 00:49:56.590942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cca80ef12b0'
down_revision: Union[str, Sequence[str], None] = '6e80d84ff9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_alerts', sa.Column('signal_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_alerts', 'signal_scores')
    # ### end Alembic commands ###
