"""Add last_seen_at

Revision ID: 6e80d84ff9c2
Revises: f7909135bec7
Create Date: 2026-08-22 14:31:09.156460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e80d84ff9c2'
down_revision: Union[str, Sequence[str], None] = 'f7909135bec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'last_seen_at')
    # ### end Alembic commands ###
