"""initial_schema

Revision ID: a3aab7f35f52
Revises:
Create Date: 2026-08-22 11:45:03.584322

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3aab7f35f52"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_type_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_type_a", sa.String(length=255), nullable=False),
        sa.Column("alert_type_b", sa.String(length=255), nullable=False),
        sa.Column("co_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("confirmed_count", sa.Integer(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_type_stats")),
    )
    op.create_index(
        "ix_alert_type_stats_types",
        "alert_type_stats",
        ["alert_type_a", "alert_type_b"],
        unique=False,
    )
    op.create_table(
        "components",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("environment", sa.String(length=100), nullable=False),
        sa.Column("tenant", sa.String(length=100), nullable=False),
        sa.Column("service_tier", sa.String(length=50), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_components")),
    )
    op.create_table(
        "change_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_change_events_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_events")),
    )
    op.create_index(
        "ix_change_events_component_id_occurred_at",
        "change_events",
        ["component_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "component_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("source_tool", sa.String(length=100), nullable=False),
        sa.Column("match_method", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_component_aliases_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component_aliases")),
        sa.UniqueConstraint("alias", "source_tool", name="uq_component_aliases_alias_source_tool"),
    )
    op.create_index("ix_component_aliases_alias", "component_aliases", ["alias"], unique=False)
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_component_id", sa.Uuid(), nullable=False),
        sa.Column("to_component_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_component_id"],
            ["components.id"],
            name=op.f("fk_dependencies_from_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_component_id"],
            ["components.id"],
            name=op.f("fk_dependencies_to_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependencies")),
        sa.UniqueConstraint("from_component_id", "to_component_id", name="uq_dependencies_from_to"),
    )
    op.create_index(
        "ix_dependencies_from_component_id", "dependencies", ["from_component_id"], unique=False
    )
    op.create_index(
        "ix_dependencies_to_component_id", "dependencies", ["to_component_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_count", sa.Integer(), nullable=False),
        sa.Column("source_tool_count", sa.Integer(), nullable=False),
        sa.Column("root_cause_component_id", sa.Uuid(), nullable=True),
        sa.Column("diameter_hops", sa.Integer(), nullable=False),
        sa.Column("capped", sa.Boolean(), nullable=False),
        sa.Column("split_from_incident_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["root_cause_component_id"],
            ["components.id"],
            name=op.f("fk_incidents_root_cause_component_id_components"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["split_from_incident_id"],
            ["incidents.id"],
            name=op.f("fk_incidents_split_from_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(
        "ix_incidents_status_opened_at", "incidents", ["status", "opened_at"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_tool", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("annotations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("environment", sa.String(length=100), nullable=False),
        sa.Column("tenant", sa.String(length=100), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("bypassed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_alerts_component_id_components"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_alerts_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "ix_alerts_component_id_starts_at", "alerts", ["component_id", "starts_at"], unique=False
    )
    op.create_index("ix_alerts_fingerprint", "alerts", ["fingerprint"], unique=False)
    op.create_index("ix_alerts_incident_id", "alerts", ["incident_id"], unique=False)
    op.create_table(
        "incident_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_a", sa.Uuid(), nullable=False),
        sa.Column("incident_b", sa.Uuid(), nullable=False),
        sa.Column("link_type", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "incident_a < incident_b", name=op.f("ck_incident_links_ck_incident_links_ordering")
        ),
        sa.ForeignKeyConstraint(
            ["incident_a"],
            ["incidents.id"],
            name=op.f("fk_incident_links_incident_a_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_b"],
            ["incidents.id"],
            name=op.f("fk_incident_links_incident_b_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_links")),
        sa.UniqueConstraint("incident_a", "incident_b", name="uq_incident_links_a_b"),
    )
    op.create_table(
        "incident_splits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_incident_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resulting_incident_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("operator", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_splits_original_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_splits")),
    )
    op.create_table(
        "root_cause_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uncertain", sa.Boolean(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_root_cause_candidates_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_root_cause_candidates_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_root_cause_candidates")),
    )
    op.create_table(
        "incident_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("join_reason", sa.String(length=255), nullable=False),
        sa.Column("join_score", sa.Float(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_incident_alerts_alert_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_alerts_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_alerts")),
        sa.UniqueConstraint("incident_id", "alert_id", name="uq_incident_alerts_incident_alert"),
    )
    op.create_table(
        "incident_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("verdict", sa.String(length=50), nullable=False),
        sa.Column("operator", sa.String(length=255), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_incident_feedback_alert_id_alerts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_feedback_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_feedback")),
    )
    op.create_index(
        "ix_incident_feedback_incident_id", "incident_feedback", ["incident_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incident_feedback_incident_id", table_name="incident_feedback")
    op.drop_table("incident_feedback")
    op.drop_table("incident_alerts")
    op.drop_table("root_cause_candidates")
    op.drop_table("incident_splits")
    op.drop_table("incident_links")
    op.drop_index("ix_alerts_incident_id", table_name="alerts")
    op.drop_index("ix_alerts_fingerprint", table_name="alerts")
    op.drop_index("ix_alerts_component_id_starts_at", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_incidents_status_opened_at", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_dependencies_to_component_id", table_name="dependencies")
    op.drop_index("ix_dependencies_from_component_id", table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index("ix_component_aliases_alias", table_name="component_aliases")
    op.drop_table("component_aliases")
    op.drop_index("ix_change_events_component_id_occurred_at", table_name="change_events")
    op.drop_table("change_events")
    op.drop_table("components")
    op.drop_index("ix_alert_type_stats_types", table_name="alert_type_stats")
    op.drop_table("alert_type_stats")
    # ### end Alembic commands ###
