"""add_occurrence_count_to_alerts

Revision ID: e8030e7793dc
Revises: 4f8d089c4255
Create Date: 2026-08-22 13:53:04.342563

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8030e7793dc"
down_revision: str | Sequence[str] | None = "4f8d089c4255"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts", sa.Column("occurrence_count", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "occurrence_count")
    # ### end Alembic commands ###
