"""Add occurrence_count and resolves_alert_id

Revision ID: f7909135bec7
Revises: e8030e7793dc
Create Date: 2026-08-22 13:58:03.709249

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7909135bec7"
down_revision: str | Sequence[str] | None = "e8030e7793dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("resolves_alert_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_alerts_resolves_alert_id_alerts"),
        "alerts",
        "alerts",
        ["resolves_alert_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_alerts_resolves_alert_id_alerts"), "alerts", type_="foreignkey")
    op.drop_column("alerts", "resolves_alert_id")
    # ### end Alembic commands ###
