receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlphttp/engine:
    endpoint: http://host.docker.internal:8000
    tls:
      insecure: true
  
  debug:
    verbosity: basic

  prometheus:
    endpoint: "0.0.0.0:8889"
    metric_expiration: 60s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/engine] # , debug] # Re-enable debug when needed
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
